
export const ayurvedicMedicines: string[] = [
  "Ashwagandha",
  "Brahmi",
  "Triphala",
  "Amalaki",
  "Haritaki",
  "Bibhitaki",
  "Turmeric",
  "Neem",
  "Tulsi",
  "Guggul",
  "Shatavari",
  "Shilajit",
  "Gotu Kola",
  "Licorice",
  "Ginger",
  "Cardamom",
  "Cinnamon",
  "Clove",
  "Fennel",
  "Coriander",
  "Manjistha",
  "Arjuna",
  "Boswellia",
  "Chyawanprash",
  "Dashamula",
  "Gokshura",
  "Kaunch",
  "Pippali",
  "Vidanga",
  "Yashtimadhu",
  "Abhayarishta",
  "Amritarishta",
  "Arjunarishta",
  "Ashokarishta",
  "Balarishta",
  "Draksharishta",
  "Kutajarishta",
  "Saraswatarishta",
  "Chandraprabha Vati",
  "Arogyavardhini Vati",
  "Sanjivani Vati",
  "Sitopaladi Churna",
  "Trikatu Churna",
  "Hingwashtak Churna",
  "Avipattikar Churna",
  "Maharasnadi Kwath",
  "Kanchanar Guggulu",
  "Yograj Guggulu",
  "Triphala Guggulu",
  "Simhanada Guggulu",
  "Mahanarayan Taila",
  "Dhanwantaram Taila",
  "Kottamchukkadi Thailam",
  "Brahmi Ghrita",
  "Phala Ghrita",
];
